
- name: Starting server base
  hosts: svr
  become: yes
  vars:
    type: cluster # cluster // standalone

    #-khusus-mysql-cluster-------------------------------------------
    mysql_cluster_type: master_slave # master_master // master_slave
    #----------------------------------------------------------------

    install_mariadb: no
    install_mysql: no
    install_mongodb: yes
    install_postgresql: no
    install_redis: no

  roles:
    - mariadb
    - mongodb
    - mysql
    - postgresql
    - redis
