# Playbook for uninstall database packages + data
- name: Uninstall database
  hosts: svr
  become: yes
  vars:
    uninstall_mariadb: no # uninstalling mariadb also uninstalling mysql-common, in order to be able for reinstallation
    uninstall_mongodb: yes
    uninstall_postgresql: no
    uninstall_mysql: no
    uninstall_redis: no
  roles:
    - uninstall