# Playbook for uninstall database packages + data
- name: Uninstall database
  hosts: svr
  become: yes
  vars:
    uninstall_mariadb: yes # uninstalling mariadb also uninstalling mysql-common, in order to be able for reinstallation
    uninstall_mongodb: yes
    uninstall_postgresql: yes
    uninstall_mysql: yes
    uninstall_redis: yes
  roles:
    - uninstall